### PR TITLE
Reuse ruby version from config in metanorma/ci

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/ci/issues/103

### CODE REVIEW

**Review by maxirmx — CHANGES_REQUESTED** [review]
I suggest to install libpng on Windows with:
pacman -S --noconfirm pactoys
pacboy sync --noconfirm libpng:p

It may look like overkill but in reality it is not since it eliminates all version and environment checks

**Review by maxirmx — APPROVED** [review]
Sorry
See below, please

**Review by maxirmx — CHANGES_REQUESTED** [review]
``` 
         - os: windows-latest
            platform: x64-mingw32
            ruby: ${{ needs.prepare.outputs.default-ruby-version }}
          - os: windows-latest
            platform: x64-mingw-ucrt
           ruby: ${{ needs.prepare.outputs.default-ruby-version }}
 ```
 
 The code above may be an issue
 It worked when there were packages for 2.7 and 3.x.  I think neither x64-mingw32 on 3.x nor : x64-mingw-ucrt on 2.7 will work
 
 Probably we can just drop 2.7 and  x64-mingw32 support

**Comment by CAMOBAP** [comment]
> ```
>          - os: windows-latest
>             platform: x64-mingw32
>             ruby: ${{ needs.prepare.outputs.default-ruby-version }}
>           - os: windows-latest
>             platform: x64-mingw-ucrt
>            ruby: ${{ needs.prepare.outputs.default-ruby-version }}
> ```
> 
> The code above may be an issue It worked when there were packages for 2.7 and 3.x. I think neither x64-mingw32 on 3.x nor : x64-mingw-ucrt on 2.7 will work
> 
> Probably we can just drop 2.7 and x64-mingw32 support

Good catch, I have reverted it for Windows

**Review by maxirmx — APPROVED** [review]

**Pull request merged**
